imports:
    - { resource: config_test.yml }

framework:
    profiler:
        only_exceptions: false
        collect: true

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    
doctrine:
    dbal:
        dbname: "%database_name%_acceptance"

        
csa_guzzle:
    logger: true
    clients:
        local_test_api:
            config:
                base_url: http://localhost:8000/app_acceptance.php/